engines: 
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      complexity:
        enabled: true
  duplication:
      enabled: true
      config:
        languages:
        - javascript
          #mass_threshold: 30
  engines:
    fixme:
      enabled: true
ratings:
   paths:
   - "src"

